"""Shared case result display for Scene 1 and Scene 3 Streamlit pages.

Renders: 4-section output · uncertainty flags · audit trace expander.
"""

import re
from datetime import datetime, timezone, timedelta
from typing import Optional

import streamlit as st
import api_client
from components.stage_progress import render_stage_progress
from components.ix4_compliance import render_w8_surface, render_w9_surface

_CST = timezone(timedelta(hours=8))

_OUTPUT_CSS = """
<style>
.case-output h1 { font-size: 1.1rem !important; margin-top: 0.8rem !important; }
.case-output h2 { font-size: 1.0rem !important; margin-top: 0.6rem !important; }
.case-output h3 { font-size: 0.95rem !important; margin-top: 0.5rem !important; }
</style>
"""

_DISCLAIMER_NOTICE = (
    "**转发患者前必须包含 disclaimer（文末红色提示）**"
    " — 此为王特医生基于 AI 辅助的参考意见，不能替代面诊决断。"
)

# M-1 confidence-disclosure (jonathan MVP ruling 2026-06-04).
# Threshold = 0.70 (DW b398a6d2, starting value — configurable for M-4 post-launch calibration).
# Wording structure (DW): what can be confirmed + what can't + what's missing + how to resolve.
# Dynamic specifics ([X]/[Y]/missing materials) are generated by SC in the report sections below;
# banner references those sections rather than fabricating dynamic content at webapp layer.
_LOW_CONFIDENCE_THRESHOLD: float = 0.70
_LOW_CONFIDENCE_DISCLOSURE: str = (
    "**基于现有资料，本次诊断结论把握不足。**"
    " 能确定的部分及所需补充的资料在下方报告中已列明；"
    " 在获得补充资料前，以下意见请作初步参考，不作最终治疗依据。"
)

# CL2 direction-suppression (76db keep-1 wire-c, jonathan db2bd365, DW c7b990e0).
# Trigger: ix_hrw_cl2_convex_sna_retrusive in hrw_clinical_flag.violations (rule_id-specific,
# NOT blanket flag presence — avoids over-suppression on voice/format violations).
# Effect: force low-confidence banner + suppress direction section (s4/s2_治疗路径).
_CL2_RULE_ID: str = "ix_hrw_cl2_convex_sna_retrusive"
_CL2_DISCLOSURE: str = (
    "**⚠️ 凸凹面分型存在疑义：** 本案例面型判断存在「凸面 + 上颌偏后缩」并存信号，"
    " 可能为上颌源凹面误判为凸面的高危模式。"
    " 下方治疗方向建议**仅供参考**，请医生独立核查面型分型后再作决策，"
    " 切勿直接依照拔牙/手术方向执行。"
)
# Direction section keys per scene — suppressed when CL2 fires.
_CL2_SUPPRESS_SECTIONS: frozenset[str] = frozenset({"s4_行动建议", "s2_治疗路径"})

# v3 §13 direction_falsification gate banner (2026-06-04).
# Trigger: v3_direction_falsification_gate in hrw_clinical_flag.violations (rule_id-specific,
# NOT blanket flag presence — keep-1 c7b990e0 纪律 parallel to CL2).
# Effect: direction suppression banner + confidence advisory. NEVER block.
_DF_GATE_RULE_ID: str = "v3_direction_falsification_gate"
_DF_GATE_DISCLOSURE: str = (
    "**⚠️ 方向结论证伪未完成：** 本案例存在高危方向结论（凸面拔牙/正颌/骨性轻判断），"
    " 但证伪四查字段缺失或依据不完整。"
    " 下方治疗方向建议**仅供参考**，请医生独立核查四查证伪后再作决策，"
    " 切勿直接依照拔牙/手术方向执行。"
)
# s2_治疗路径 always suppressed when DF gate fires (firm treatment plan).
# s4_行动建议 uses mode-conditional + clause-level lexeme guard — see _df_gate_should_suppress_s4().
# 76db纪律: don't trust SC self-classification alone; thin backstop on SC mislabel.
_DF_GATE_SUPPRESS_SECTIONS: frozenset[str] = frozenset({"s2_治疗路径"})
_DF_FIRM_LEXEMES: re.Pattern = re.compile(r'拔牙|拔除|减数|正颌|手术|BSSO|Le\s*Fort')
_DF_CONDITIONAL_MARKERS: re.Pattern = re.compile(r'^(若|如果|倘若|假如|若证实|如)')

_V4_REVIEW_DISCLOSURE: str = (
    "**⚠️ 诊断仍需复核：** 本案例存在尚未确定的分型疑义或证据不足路径。"
    " 请医生重点核查下方报告与影像依据，在疑义明确前不要将其视为最终治疗方向。"
)

_V4_REASON_LABELS: dict[str, str] = {
    "retreatment_history=second_treatment_and_prior_extraction": "既往拔牙 + 二次矫治会改变面型来源判断，需要人工复核/补病史。",
    "retreatment_history=suspected_extraction_retraction_history": "既往拔牙/内收/关闭间隙史疑似但未确认，来源归因暂不能高置信判断。",
    "missing_or_conflicting_required_closure_anchors": "关键证据缺失或互相冲突，当前还不能确定分型。",
    "maxillary_support=deficient": "存在上颌支撑不足信号，需要复核上颌来源风险。",
    "maxillary_support=unreadable_with_source_risk_context": "上颌支撑读片不清，但同时存在来源风险锚点，需要复核。",
    "arch_palate=strict_narrow_high": "上颌弓窄/腭穹高是来源风险锚点，但不能单独诊断上颌源凹面。",
    "maxillary_arch_form=narrow_or_high_palate": "上颌弓形窄或腭穹高支持复核风险，但不能单独诊断。",
    "incisor_compensation=compensated_positive_overjet": "正覆盖可能受牙性代偿影响，不能单凭正覆盖排除凹面来源风险。",
    "upper_incisor_compensation=proclined": "上前牙唇倾代偿可能遮盖真实来源，需要结合其他证据复核。",
    "lower_incisor_compensation=retroclined_or_upright_compensation": "下前牙直立/舌倾代偿可能遮盖真实来源，需要结合其他证据复核。",
    "molar_relation_sagittal=mesial": "磨牙近中关系是 III 类/凹面风险锚点之一，需要结合其他证据复核。",
    "posterior_crossbite=present_unilateral": "单侧后牙反𬌗提示横向/上颌风险，需要复核。",
    "posterior_crossbite=present_bilateral": "双侧后牙反𬌗提示横向/上颌风险，需要复核。",
}

_V4_FIELD_QUESTIONS: dict[str, str] = {
    "prior_treatment_history": "请补充既往是否矫治过、是否拔牙、是否做过内收或关闭间隙。",
    "prior_extraction_retraction": "请确认既往拔牙/内收/关闭间隙史，最好提供原始病历或拔牙位点。",
    "molar_canine_relation": "请补充清晰左右侧咬合照，用于判断磨牙/尖牙关系。",
    "posterior_crossbite": "请补充后牙咬合和横向关系照片，确认是否存在后牙反𬌗或上颌横向不足。",
    "maxillary_support": "请补充标准侧貌照/头影或 CBCT 资料，用于复核上颌支撑。",
    "paranasal_support": "请问是否觉得鼻子两边偏平？选太阳镜时是否更适合大框？",
    "maxillary_arch_form": "请补充上颌牙弓照片或口扫，用于判断牙弓狭窄、腭穹高或拥挤来源。",
}

_V4_SOURCE_LABELS: dict[str, str] = {
    "maxillary_primary_candidate": "上颌来源候选",
    "mandibular_primary_candidate": "下颌 / III 类来源候选",
    "bimaxillary_candidate": "双颌 / 牙槽前突候选",
    "dental_compensation_dominant": "牙性代偿主导候选",
    "unresolved": "来源仍未确定",
}

_V4_ATTRIBUTION_LEVEL_LABELS: dict[str, str] = {
    "likely": "目前证据倾向支持，但需要正式测量确认",
    "review_candidate": "需要复核，暂不能确定",
    "possible": "可能相关",
    "unresolved": "仍未确定",
}

_V4_CANNOT_CLOSE_LABELS: dict[str, str] = {
    "phase1_review_gate_still_visible": "关键矢状证据仍需复核，不能直接定为最终来源。",
    "phase1_unresolved_gate_preserved": "现有证据不足或互相冲突，来源暂时不能确定。",
    "retreatment_extraction_history_requires_human_review": "既往矫治或拔牙史会改变来源判断，需要人工复核。",
    "phase1_clean_gate_explanation_only": "当前仅作为来源解释，不额外增加复核要求。",
}

_V4_SUBTYPE_FAMILY_LABELS: dict[str, str] = {
    "skeletal_maxillary_source": "以上颌来源为主的凹面候选",
    "skeletal_mandibular_source": "以下颌 / III 类来源为主的凹面候选",
    "skeletal_upper_lower_source": "上下颌共同参与的凹面候选",
    "dentoalveolar_compensation": "牙槽代偿主导候选",
    "unresolved": "亚型仍未确定",
}

_V4_UPPER_LOWER_SUBTYPE_LABELS: dict[str, str] = {
    "triangular_deep_concave": "深凹 / 上下颌差异较明显候选",
    "triangular_shallow_concave": "下颌三角浅凹待正式测量确认",
    "shallow_false_protrusive_concave": "上下源性凹面方向；下颌三角浅凹待正式测量确认",
    "true_concave_false_protrusive_risk": "凹面方向伴假突表现风险，待正式测量确认",
    "maxillary_transverse_deficiency": "上颌横向不足参与候选",
    "unresolved": "上下颌亚型仍未确定",
}

_V4_FIELD_LABELS: dict[str, str] = {
    "formal_ceph": "正式头影测量",
    "formal_ceph_measurements": "正式头影测量",
    "cephalometric_tracing": "正式头影测量",
    "crco": "CR-CO / 功能移位记录",
    "centric_relation_record": "CR-CO / 功能移位记录",
    "functional_shift": "功能移位记录",
    "prior_treatment_history": "既往矫治史",
    "prior_extraction_retraction": "既往拔牙/内收/关闭间隙史",
    "molar_canine_relation": "磨牙/尖牙关系",
    "posterior_crossbite": "后牙横向关系",
    "maxillary_support": "上颌支撑",
    "paranasal_support": "鼻旁区支撑",
    "maxillary_arch_form": "上颌牙弓形态",
    "arch_palate": "牙弓宽度 / 腭穹形态",
}


def _cl2_fired(case: dict) -> bool:
    """Return True if HRW-CL2 (ix_hrw_cl2_convex_sna_retrusive) fired for this case."""
    stage_e = (case.get("stage_info") or {}).get("stage_E_hrw") or {}
    flag = stage_e.get("hrw_clinical_flag") or {}
    violations = flag.get("violations") or []
    return any(v.get("rule_id") == _CL2_RULE_ID for v in violations)


def _falsification_incomplete(case: dict) -> bool:
    """Return True if v3 §13 direction_falsification gate fired for this case."""
    stage_e = (case.get("stage_info") or {}).get("stage_E_hrw") or {}
    flag = stage_e.get("hrw_clinical_flag") or {}
    violations = flag.get("violations") or []
    return any(v.get("rule_id") == _DF_GATE_RULE_ID for v in violations)


def _df_gate_should_suppress_s4(content: str, voice_mode: str) -> bool:
    """Mode-conditional + clause-level lexeme guard for s4_行动建议 when DF gate fired.

    Mode A / unknown → always suppress (firm direction without falsification = dangerous).
    Mode B → suppress only if s4 contains a firm-direction lexeme OUTSIDE a conditional bracket.
    DW Mode B invariant (SC L550): Mode B s4 must use bracketed conditionals for any direction.
    76db discipline: don't trust SC self-classification alone — keep thin backstop for mislabel.
    """
    if voice_mode != "B_difficult_diagnosis_warning":
        return True  # Mode A or unknown → suppress (safe default)
    for clause in re.split(r'[。；\n]', content or ""):
        clause = clause.strip()
        if clause and _DF_FIRM_LEXEMES.search(clause):
            if not _DF_CONDITIONAL_MARKERS.search(clause):
                # Firm imperative outside conditional bracket → SC mislabel detected → suppress
                return True
    return False  # All firm lexemes in conditional brackets (W8 compliant) → keep


def _v4_review_required(case: dict, final_output: Optional[dict] = None) -> bool:
    """V4 Phase I frontend surface: review-required gates must be visible, not metadata-only."""
    final_output = final_output or {}
    prompt = final_output.get("v4_review_prompt") or {}
    if prompt.get("visible"):
        return True
    meta = case.get("metadata") or {}
    v4 = meta.get("v4_phase1") or {}
    gate = v4.get("v4_gate_packet") or {}
    gate_result = gate.get("gate_result")
    sc_status = v4.get("v4_sc_gate_consistency") or {}
    if gate_result and gate_result != "true_convex_closed":
        return True
    if sc_status.get("consistent") is False:
        return True
    if sc_status.get("anchor_dispute_present"):
        return True
    return False


def _v4_phase1_packet(case: dict, final_output: Optional[dict] = None) -> dict:
    final_output = final_output or {}
    phase1 = final_output.get("v4_phase1")
    if isinstance(phase1, dict) and phase1:
        return phase1
    meta = case.get("metadata") or {}
    phase1 = meta.get("v4_phase1")
    return phase1 if isinstance(phase1, dict) else {}


def _v4_phase2_packet(case: dict, final_output: Optional[dict] = None) -> dict:
    """V4 Phase II frontend surface: source attribution is explanation-only."""
    final_output = final_output or {}
    phase2 = final_output.get("v4_phase2") or {}
    packet = phase2.get("source_attribution_packet") if isinstance(phase2, dict) else None
    if isinstance(packet, dict) and packet:
        return packet
    meta = case.get("metadata") or {}
    phase2 = meta.get("v4_phase2") or {}
    packet = phase2.get("source_attribution_packet") if isinstance(phase2, dict) else None
    return packet if isinstance(packet, dict) else {}


def _render_v4_source_explanation(case: dict, final_output: Optional[dict] = None):
    final_output = final_output or {}
    explanation = final_output.get("v4_source_explanation") or {}
    packet = _v4_phase2_packet(case, final_output)
    if not (explanation.get("visible") or packet):
        return

    source_key = packet.get("source_candidate") or explanation.get("source_candidate") or "unresolved"
    label = explanation.get("source_label") or _V4_SOURCE_LABELS.get(source_key, "来源仍需复核")
    level_key = explanation.get("attribution_level") or packet.get("attribution_level") or "unresolved"
    level = _V4_ATTRIBUTION_LEVEL_LABELS.get(level_key, str(level_key))
    reason_key = explanation.get("cannot_close_reason") or packet.get("cannot_close_reason") or "missing_or_conflicting_source_anchors"
    reason = _V4_CANNOT_CLOSE_LABELS.get(reason_key, str(reason_key))
    st.info(
        f"**来源判断（供医生复核）：** {label}；"
        f"{level}；原因：{reason}"
        " 这只是对现有证据的解释，不能替代正式测量和面诊判断。"
    )

    groups = [
        ("决定性证据", packet.get("decisive_anchors") or []),
        ("支持性证据", packet.get("supporting_anchors") or []),
        ("相反证据", packet.get("conflicting_anchors") or []),
        ("仍缺资料", packet.get("missing_required_anchors") or []),
    ]
    total = sum(len(items) for _, items in groups if isinstance(items, list))
    if total:
        with st.expander("来源判断依据", expanded=False):
            for title, items in groups:
                if not isinstance(items, list) or not items:
                    continue
                st.markdown(f"**{title}**")
                for item in items[:8]:
                    if isinstance(item, dict):
                        raw_anchor = item.get("anchor") or item.get("field") or "证据"
                        anchor = _human_anchor_label(str(raw_anchor))
                        note = item.get("note") or item.get("reason") or ""
                        st.markdown(f"- {anchor}: {note}" if note else f"- {anchor}")
                    else:
                        st.markdown(f"- {item}")


def _plain_reason_from_blocker(blocker: str) -> str:
    if blocker in _V4_REASON_LABELS:
        return _V4_REASON_LABELS[blocker]
    if blocker.startswith("retreatment_history="):
        return "既往矫治/拔牙相关信息影响来源判断，需要人工复核。"
    if blocker in {"source_gap_unknown", "unreadable"}:
        return "来源相关证据不完整，需要补充资料。"
    if "=" in blocker:
        field, value = blocker.split("=", 1)
        return f"{_V4_FIELD_LABELS.get(field, field)} 是复核证据之一；请结合其他证据判断，不能单独作为最终诊断。"
    return blocker


def _human_anchor_label(anchor: str) -> str:
    if "=" in anchor:
        field, value = anchor.split("=", 1)
        field_label = _V4_FIELD_LABELS.get(field, field)
        if field_label != field:
            return field_label
        return anchor
    return _V4_FIELD_LABELS.get(anchor, anchor)


def _review_reason_items(case: dict, final_output: Optional[dict] = None) -> list[str]:
    phase1 = _v4_phase1_packet(case, final_output)
    gate = phase1.get("v4_gate_packet") or {}
    blockers = list(gate.get("blocking_reasons") or [])
    history = phase1.get("v4_retreatment_history_packet") or _v4_phase2_field(case, final_output, "retreatment_history_packet")
    if isinstance(history, dict) and history.get("review_required"):
        for reason in history.get("reasons") or []:
            blockers.append(f"retreatment_history={reason}")
    source = _v4_phase2_packet(case, final_output)
    if source.get("cannot_close_reason") in {
        "missing_or_conflicting_source_anchors",
        "retreatment_extraction_history_requires_human_review",
        "review_required_supporting_anchors_only",
    }:
        blockers.append(source.get("cannot_close_reason"))
    for item in source.get("missing_required_anchors") or []:
        if isinstance(item, dict):
            field = item.get("field")
            if field:
                blockers.append(f"missing:{field}")

    seen = set()
    reasons = []
    for blocker in blockers:
        if not blocker or blocker in seen:
            continue
        seen.add(blocker)
        if str(blocker).startswith("missing:"):
            field = str(blocker).split(":", 1)[1]
            field_label = _V4_FIELD_LABELS.get(field, field)
            reasons.append(f"缺少{field_label}，需补充后再判断。")
        elif blocker == "review_required_supporting_anchors_only":
            reasons.append("当前仅能形成复核候选，不能把风险锚点当作最终诊断。")
        elif blocker == "retreatment_extraction_history_requires_human_review":
            reasons.append("二次矫治/拔牙史会限制自动来源归因，需要人工复核。")
        else:
            reasons.append(_plain_reason_from_blocker(str(blocker)))
    return reasons[:8]


def _supplement_questions(case: dict, final_output: Optional[dict] = None) -> list[str]:
    source = _v4_phase2_packet(case, final_output)
    phase1 = _v4_phase1_packet(case, final_output)
    gate = phase1.get("v4_gate_packet") or {}
    raw_text = " ".join(str(v) for v in (
        gate.get("blocking_reasons") or []
        + [item.get("field") for item in (source.get("missing_required_anchors") or []) if isinstance(item, dict)]
    ) if v)

    questions = []
    def add(field: str):
        text = _V4_FIELD_QUESTIONS.get(field)
        if text and text not in questions:
            questions.append(text)

    for item in source.get("missing_required_anchors") or []:
        if isinstance(item, dict):
            add(str(item.get("field") or ""))
    for field in _V4_FIELD_QUESTIONS:
        if field in raw_text:
            add(field)
    if any(token in raw_text for token in ("paranasal_support", "maxillary_support=deficient")):
        add("paranasal_support")
    if any(token in raw_text for token in ("posterior_crossbite", "maxillary_arch_form", "arch_palate")):
        add("posterior_crossbite")
    return questions[:6]


def _render_v4_uncertainty_workflow(case: dict, final_output: Optional[dict] = None):
    review_active = _v4_review_required(case, final_output)
    source = _v4_phase2_packet(case, final_output)
    subtype = _v4_phase2_field(case, final_output, "v4_shengang_subtype") or _v4_phase2_field(
        case, final_output, "shengang_concave_subtype_packet"
    )
    advisory = _v4_phase2_field(case, final_output, "v4_treatment_advisory") or _v4_phase2_field(
        case, final_output, "treatment_template_advisory"
    )
    has_concrete_blocker = bool(_review_reason_items(case, final_output) or advisory.get("visible"))
    if not (review_active or has_concrete_blocker or subtype.get("scope_applies")):
        return

    reasons = _review_reason_items(case, final_output)
    if reasons:
        with st.expander("为什么需要复核", expanded=True):
            for reason in reasons:
                st.markdown(f"- {reason}")

    if subtype.get("scope_applies"):
        family = subtype.get("shen_concave_family") or "unresolved"
        upper_lower = subtype.get("upper_lower_subtype") or "unresolved"
        family_label = _V4_SUBTYPE_FAMILY_LABELS.get(family, str(family))
        upper_lower_label = _V4_UPPER_LOWER_SUBTYPE_LABELS.get(upper_lower, str(upper_lower))
        title = "可能方向 / 待复核" if "unresolved" in {family, upper_lower} else "来源和亚型提示"
        st.info(
            f"**{title}：** {family_label}；{upper_lower_label}。"
            " 这是给医生的证据解释，不能替代正式测量后的最终诊断。"
        )

    questions = _supplement_questions(case, final_output)
    if questions:
        with st.expander("建议补充的问题 / 资料", expanded=True):
            for question in questions:
                st.markdown(f"- {question}")

    if advisory.get("visible"):
        st.info("**治疗边界提示：** " + str(advisory.get("message") or ""), icon="ℹ️")


def _v4_phase2_field(case: dict, final_output: Optional[dict], field: str) -> dict:
    final_output = final_output or {}
    value = final_output.get(field)
    if isinstance(value, dict) and value:
        return value
    phase2 = final_output.get("v4_phase2") or {}
    if isinstance(phase2, dict):
        value = phase2.get(field)
        if isinstance(value, dict) and value:
            return value
    meta = case.get("metadata") or {}
    value = meta.get(field)
    if isinstance(value, dict) and value:
        return value
    phase2 = meta.get("v4_phase2") or {}
    if isinstance(phase2, dict):
        value = phase2.get(field)
        if isinstance(value, dict) and value:
            return value
    return {}


def _render_v4_reassessment_surfaces(case: dict, final_output: Optional[dict] = None):
    phase1 = (final_output or {}).get("v4_phase1") or (case.get("metadata") or {}).get("v4_phase1") or {}
    history_packet = phase1.get("v4_retreatment_history_packet") if isinstance(phase1, dict) else None
    if not isinstance(history_packet, dict):
        history_packet = _v4_phase2_field(case, final_output, "retreatment_history_packet")
    if history_packet.get("review_required"):
        st.warning(
            "**复治/拔牙史复核：** "
            + (history_packet.get("human_review_message")
               or "既往拔牙或二次矫治会明显改变面型来源判断，需要人工复核/补病史。"),
            icon="⚠️",
        )

    subtype = _v4_phase2_field(case, final_output, "v4_shengang_subtype") or _v4_phase2_field(
        case, final_output, "shengang_concave_subtype_packet"
    )
    if subtype.get("scope_applies"):
        family = subtype.get("shen_concave_family", "unresolved")
        upper_lower = subtype.get("upper_lower_subtype", "unresolved")
        st.info(
            "**凹面来源和亚型（供医生复核）：** "
            f"{_V4_SUBTYPE_FAMILY_LABELS.get(family, str(family))}；"
            f"{_V4_UPPER_LOWER_SUBTYPE_LABELS.get(upper_lower, str(upper_lower))}。"
            " 证据不足时会保持未确定，不从单个风险信号强行诊断。"
        )

    advisory = _v4_phase2_field(case, final_output, "v4_treatment_advisory") or _v4_phase2_field(
        case, final_output, "treatment_template_advisory"
    )
    if advisory.get("visible"):
        st.info("**成人凹面治疗边界：** " + str(advisory.get("message") or ""), icon="ℹ️")


def _to_cst(utc_str: str) -> str:
    try:
        dt = datetime.fromisoformat(utc_str).replace(tzinfo=timezone.utc)
        return dt.astimezone(_CST).strftime("%Y-%m-%d %H:%M CST")
    except Exception:
        return utc_str[:16].replace("T", " ")

_SECTION_LABELS = {
    # v2 semantic keys (SC v1, spec freeze v1 § 3)
    "s1_情况判读": "一、情况判读",
    "s2_面诊重点": "二、面诊重点",
    "s3_配合事项": "三、配合事项",
    "s4_行动建议": "四、行动建议",
    # v2 Scene 3 keys
    "s1_临床推理": "一、临床推理",
    "s2_治疗路径": "二、治疗路径",
    "s3_3_school_compare": "三、关节相关框架边界",
    "s4_要点提醒": "四、要点提醒",
    # v1 fallback keys (existing done cases)
    "section1_patient_summary_or_diagnosis": "一、患者摘要与诊断",
    "section2_treatment_or_followup": "二、治疗方案 / 随访建议",
    "section3_validation_notes": "三、验证说明",
    "section4_calls_to_action": "四、下一步行动",
}

_SCHOOL_SECTION_KEYS: frozenset[str] = frozenset({"s3_3_school_compare"})
_SCHOOL_COMPARE_REQUEST_RE: re.Pattern = re.compile(
    r"三学派|学派对比|流派对比|框架对比|framework\s+comparison|school\s+comparison",
    re.IGNORECASE,
)
_JOINT_BOUNDARY_RE: re.Pattern = re.compile(
    r"TMJ|TMD|颞下颌|颞颌|髁突|关节盘|张口受限|开口受限|弹响|"
    r"关节痛|疼痛|吸收|退变|关节稳定|正颌.{0,12}关节|关节.{0,12}正颌",
    re.IGNORECASE,
)
_JOINT_NEGATIVE_RE: re.Pattern = re.compile(
    r"无关节|关节目前稳定|关节稳定[,，、 ]*无|无疼痛|无痛|无弹响|"
    r"无张口受限|无开口受限|无活动性症状|无明显症状"
)
_EMPTY_SIGNAL_RE: re.Pattern = re.compile(r"^\s*(无|暂无|没有|不明|未知|none|null|n/a|—|-)\s*$", re.IGNORECASE)


def _text_values(value) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, dict):
        texts = []
        for item in value.values():
            texts.extend(_text_values(item))
        return texts
    if isinstance(value, (list, tuple)):
        texts = []
        for item in value:
            texts.extend(_text_values(item))
        return texts
    return []


def _meaningful_signal(value) -> bool:
    if value is None:
        return False
    if isinstance(value, str):
        return bool(value.strip()) and not _EMPTY_SIGNAL_RE.match(value)
    if isinstance(value, (list, tuple)):
        return any(_meaningful_signal(item) for item in value)
    if isinstance(value, dict):
        return any(_meaningful_signal(item) for item in value.values())
    return bool(value)


def _explicit_school_compare_requested(submission: dict) -> bool:
    request_fields = {
        "chief_complaint_patient": submission.get("chief_complaint_patient"),
        "chief_complaint_doctor": submission.get("chief_complaint_doctor"),
        "chief_complaint_main_concern": submission.get("chief_complaint_main_concern"),
        "doctor_specific_question": submission.get("doctor_specific_question"),
        "context_notes": submission.get("context_notes"),
    }
    return any(_SCHOOL_COMPARE_REQUEST_RE.search(text) for text in _text_values(request_fields))


def _joint_boundary_relevant(submission: dict) -> bool:
    findings = submission.get("clinical_findings") or {}
    if isinstance(findings, dict):
        tmd = findings.get("tmd_signals") or {}
        if isinstance(tmd, dict):
            structured_fields = (
                tmd.get("active_symptoms"),
                tmd.get("symptom_progression"),
                tmd.get("cbct_findings"),
                tmd.get("mri_findings"),
            )
            if any(_meaningful_signal(field) for field in structured_fields):
                return True

    boundary_fields = {
        "chief_complaint_patient": submission.get("chief_complaint_patient"),
        "chief_complaint_doctor": submission.get("chief_complaint_doctor"),
        "chief_complaint_main_concern": submission.get("chief_complaint_main_concern"),
        "doctor_specific_question": submission.get("doctor_specific_question"),
        "context_notes": submission.get("context_notes"),
    }
    for text in _text_values(boundary_fields):
        if _JOINT_BOUNDARY_RE.search(text) and not _JOINT_NEGATIVE_RE.search(text):
            return True
    return False


def _should_render_school_section(case: dict, final_output: Optional[dict] = None) -> bool:
    submission = case.get("submission") or {}
    return _explicit_school_compare_requested(submission) or _joint_boundary_relevant(submission)


def _has_school_section(sections: dict) -> bool:
    return isinstance(sections, dict) and any(key in _SCHOOL_SECTION_KEYS for key in sections)


def _strip_school_markdown_section(markdown: str) -> str:
    if not markdown:
        return markdown
    pattern = re.compile(
        r"(?ms)^#{1,4}\s*三[、.．]\s*(?:3-school|三学派|学派|框架).*?"
        r"(?=^#{1,4}\s*(?:四[、.．]|4[、.．])|\Z)"
    )
    return pattern.sub("", markdown).strip()


def _render_input_recap(submission: dict, scene: str):
    """Show original consultation input above the AI result for comparison."""
    if not submission:
        return

    with st.expander("📋 咨询时提交的内容", expanded=True):
        if not scene.startswith("3"):
            # ── Scene 1 ──────────────────────────────────────────────────────
            age = submission.get("patient_age")
            gender = submission.get("patient_gender")
            complaint = submission.get("chief_complaint") or ""
            attachment_meta = submission.get("attachment_meta") or []
            attachment_ids = submission.get("attachment_ids") or []

            demo_parts = []
            if age:
                demo_parts.append(f"**年龄：** {age} 岁")
            if gender:
                demo_parts.append(f"**性别：** {gender}")
            if demo_parts:
                st.markdown("  ·  ".join(demo_parts))
            if complaint:
                st.markdown("**主诉内容：**")
                st.markdown(complaint)
            n = len(attachment_meta or attachment_ids)
            if n:
                st.markdown(f"**影像 / 照片**（{n} 张）")
                for i, a in enumerate(attachment_meta or []):
                    aid = a.get("id", "")
                    fname = a.get("filename", a.get("id", f"附件 #{i+1}"))
                    mime = a.get("mime_type", "")
                    if aid and mime.startswith("image/"):
                        try:
                            st.image(api_client.get_attachment_bytes(aid), width=300, caption=fname)
                        except Exception:
                            st.caption(f"📎 {fname}")
                    else:
                        st.caption(f"📎 {fname}")
                if not attachment_meta:
                    for i, aid in enumerate(attachment_ids):
                        st.caption(f"📎 附件 #{i+1}: {aid[:8]}…")

        else:
            # ── Scene 3 ──────────────────────────────────────────────────────
            submitter_role = submission.get("submitter_role")
            institution = submission.get("institution")
            age = submission.get("patient_age")
            age_conf = submission.get("patient_age_confidence", "high")
            sex = submission.get("patient_sex")

            if submitter_role or institution or age or sex:
                demo_parts = []
                if submitter_role:
                    demo_parts.append(f"**提交者：** {submitter_role}")
                if institution:
                    demo_parts.append(f"**机构：** {institution}")
                if age:
                    age_str = f"{age} 岁"
                    if age_conf != "high":
                        age_str += f"（{age_conf}）"
                    demo_parts.append(f"**患者年龄：** {age_str}")
                if sex:
                    demo_parts.append(f"**性别：** {sex}")
                st.markdown("  ·  ".join(demo_parts))

            cp_patient = submission.get("chief_complaint_patient")
            cp_doctor = submission.get("chief_complaint_doctor")
            cp_concern = submission.get("chief_complaint_main_concern")
            if cp_patient or cp_doctor:
                st.markdown("---")
                st.markdown("**主诉**")
                if cp_patient:
                    st.markdown(f"*患者陈述：* {cp_patient}")
                if cp_doctor:
                    st.markdown(f"*医生摘要：* {cp_doctor}")
                if cp_concern and cp_concern != "多项":
                    st.markdown(f"*主要关注：* {cp_concern}")

            cf = submission.get("clinical_findings") or {}
            if isinstance(cf, dict) and any(cf.values()):
                st.markdown("---")
                st.markdown("**临床发现**")
                if cf.get("face"):
                    st.markdown(f"*面型：* {cf['face']}")
                if cf.get("intraoral"):
                    st.markdown(f"*口内：* {cf['intraoral']}")
                if cf.get("dental_findings"):
                    st.markdown(f"*牙体：* {cf['dental_findings']}")
                tmd = cf.get("tmd_signals") or {}
                if isinstance(tmd, dict):
                    symptoms = tmd.get("active_symptoms") or []
                    if symptoms:
                        st.markdown(f"*TMD 症状：* {', '.join(symptoms)}")
                    prog = tmd.get("symptom_progression")
                    if prog and prog != "不明":
                        st.markdown(f"*症状进展：* {prog}")
                    if tmd.get("cbct_findings"):
                        st.markdown(f"*CBCT：* {tmd['cbct_findings']}")
                    if tmd.get("mri_findings"):
                        st.markdown(f"*MRI：* {tmd['mri_findings']}")
                ceph = cf.get("cephalometric_estimates") or {}
                if isinstance(ceph, dict):
                    ceph_parts = [
                        f"{k.upper()}={ceph[k]}"
                        for k in ("anb", "snb", "wits", "u1_l1")
                        if ceph.get(k) is not None
                    ]
                    if ceph_parts:
                        st.markdown(
                            f"*头影测量：* {', '.join(ceph_parts)}"
                            f"（置信度：{ceph.get('estimate_confidence', '—')}）"
                        )

            imaging = submission.get("imaging_provided") or []
            meta_by_id = submission.get("_imaging_meta_by_id") or {}
            if imaging:
                st.markdown("---")
                st.markdown(f"**影像资料**（{len(imaging)} 项）")
                for item in imaging:
                    aid = item.get("attachment_id", "")
                    m = meta_by_id.get(aid, {})
                    fname = m.get("filename", aid[:8] + "…" if aid else "—")
                    mime = m.get("mime_type", "")
                    desc = f"{fname} — {item.get('type', '')}"
                    if item.get("view"):
                        desc += f" ({item['view']})"
                    if aid and mime.startswith("image/"):
                        try:
                            st.image(api_client.get_attachment_bytes(aid), width=300, caption=desc)
                        except Exception:
                            st.caption(f"📎 {desc}")
                    else:
                        st.caption(f"📎 {desc}")

            prior_hist = submission.get("prior_treatment_history")
            prior_school = submission.get("prior_school_framework")
            if prior_hist or prior_school:
                st.markdown("---")
                st.markdown("**既往治疗**")
                if prior_hist:
                    st.markdown(f"*病史：* {prior_hist}")
                if prior_school:
                    st.markdown(f"*学派：* {prior_school}")

            prefs = []
            if submission.get("patient_pref_no_surgery"):
                prefs.append("不接受手术")
            if submission.get("patient_pref_time_priority"):
                prefs.append("时间优先")
            if prefs:
                st.markdown("---")
                st.markdown(f"**患者意愿：** {' · '.join(prefs)}")

            q = submission.get("doctor_specific_question")
            if q:
                st.markdown("---")
                st.markdown("**医生提问：**")
                st.markdown(q)

            notes = submission.get("context_notes")
            if notes:
                st.markdown("---")
                st.markdown("**备注：**")
                st.markdown(notes)


def render_result(case_id: str, case: dict):
    """Render complete case result: output + input recap + uncertainty flags + audit trace."""
    fo = case.get("final_output") or {}
    md = fo.get("rendered_markdown", "")
    sections = fo.get("sections", {})
    word_count = fo.get("word_count", 0)
    meta = case.get("metadata", {})

    # Submission + completion timestamps (Change 39)
    time_parts = []
    if case.get("submitted_at"):
        time_parts.append(f"提交: {_to_cst(case['submitted_at'])}")
    if case.get("completed_at") and case.get("status") in ("done", "awaiting_doctor_review", "escalated", "failed"):
        time_parts.append(f"产出: {_to_cst(case['completed_at'])}")
    if time_parts:
        st.caption("  ·  ".join(time_parts))

    confidence = (meta.get("phase_results") or {}).get("B", {}).get("confidence")
    voice_mode_label = fo.get("voice_mode_applied", "")
    caption_parts = []
    if confidence is not None:
        caption_parts.append(f"📊 置信度: {confidence:.0%}")
    if voice_mode_label == "B_difficult_diagnosis_warning":
        caption_parts.append("🔴 Mode B（难症）")
    elif voice_mode_label == "A_standard":
        caption_parts.append("🟢 Mode A（标准）")
    if caption_parts:
        st.caption("  ·  ".join(caption_parts))

    # IX-4 W8: diagnose-or-explain surface (RD-1a)
    render_w8_surface(case)

    # STAGE_INFO completed history (sidebar-style)
    stage_info = case.get("stage_info") or {}
    if stage_info:
        with st.expander("📊 处理阶段详情", expanded=False):
            render_stage_progress(stage_info)

    # ── Input recap ──
    _render_input_recap(case.get("submission") or {}, case.get("scene", ""))

    # ── Voice mode surface (O-4: 说人话 layer) ──
    voice_mode = fo.get("voice_mode_applied", "")
    if voice_mode == "B_difficult_diagnosis_warning":
        st.warning(
            "⚠️ **难症警告**：本案例涉及较高诊断不确定性，AI 分析存在分歧或置信度偏低。"
            " 建议医生重点审阅，不宜直接转发患者。",
            icon="⚠️",
        )

    # ── CL2 wire-c: 凸凹误判高危 banner + direction suppression (DW c7b990e0, jonathan db2bd365) ──
    cl2_active = _cl2_fired(case)
    if cl2_active:
        st.error(_CL2_DISCLOSURE, icon="🚨")

    # ── v3 §13 direction_falsification gate banner + direction suppression (2026-06-04) ──
    df_active = _falsification_incomplete(case)
    if df_active:
        st.error(_DF_GATE_DISCLOSURE, icon="🚨")

    # ── V4 Phase I gate-stability banner (visible review/questionable surface) ──
    v4_review_active = _v4_review_required(case, fo)
    if v4_review_active:
        st.warning(_V4_REVIEW_DISCLOSURE, icon="⚠️")
    _render_v4_uncertainty_workflow(case, fo)
    _render_v4_source_explanation(case, fo)

    # ── M-1 confidence-disclosure (MVP: low confidence → show output with label, no blocking) ──
    # Threshold and wording are DW-owned constants (_LOW_CONFIDENCE_THRESHOLD / _LOW_CONFIDENCE_DISCLOSURE).
    # Mode B warning (above) is voice-mode driven; this is numeric-threshold driven — both can fire.
    if confidence is not None and confidence < _LOW_CONFIDENCE_THRESHOLD:
        st.warning(_LOW_CONFIDENCE_DISCLOSURE, icon="ℹ️")

    # ── Main output ──
    suppress_active = cl2_active or df_active
    render_school_section = _should_render_school_section(case, fo)
    has_school_section = _has_school_section(sections)
    if md or sections:
        st.markdown(_OUTPUT_CSS, unsafe_allow_html=True)
        if (case.get("scene") or "").startswith("1"):
            st.error(_DISCLAIMER_NOTICE, icon="⚠️")
        if md and not sections and not render_school_section:
            # Legacy fallback when only rendered_markdown exists: remove a standalone
            # three-school/framework block if it was materialized into markdown.
            st.markdown(_strip_school_markdown_section(md))
        elif md and not suppress_active and not has_school_section:
            # Render pre-built markdown directly when no suppression gate has fired.
            st.markdown(md)
        else:
            # Suppression active (CL2 or DF gate): fall back to per-section rendering.
            # Also used as fallback when no rendered_markdown is available.
            render_sections = sections or {}
            for key, content in render_sections.items():
                if key in _SCHOOL_SECTION_KEYS and not render_school_section:
                    continue
                if cl2_active and key in _CL2_SUPPRESS_SECTIONS:
                    label = _SECTION_LABELS.get(key, key)
                    st.markdown(f"### {label}")
                    st.warning(
                        "⚠️ **治疗方向暂不自动展示**（CL2 凸凹面疑义）。"
                        " 请医生独立核查面型分型后再决策。",
                        icon="⚠️",
                    )
                    st.divider()
                    continue
                if df_active:
                    # s2: always suppress; s4: mode-conditional + clause-level lexeme guard
                    _df_suppress = (key in _DF_GATE_SUPPRESS_SECTIONS) or (
                        key == "s4_行动建议"
                        and _df_gate_should_suppress_s4(content or "", voice_mode)
                    )
                    if _df_suppress:
                        label = _SECTION_LABELS.get(key, key)
                        st.markdown(f"### {label}")
                        st.warning(
                            "⚠️ **治疗方向暂不自动展示**（方向证伪未完成）。"
                            " 请医生独立核查四查证伪后再决策。",
                            icon="⚠️",
                        )
                        st.divider()
                        continue
                label = _SECTION_LABELS.get(key, key)
                st.markdown(f"### {label}")
                st.markdown(content)
                st.divider()

    # ── Image-claim binding (Scene 3, doctor-facing) ──
    image_anchors = fo.get("image_anchors") or []
    if image_anchors and not render_school_section:
        image_anchors = [a for a in image_anchors if a.get("section") not in _SCHOOL_SECTION_KEYS]
    if image_anchors and (case.get("scene") or "").startswith("3"):
        with st.expander(f"🔍 影像诊断依据（{len(image_anchors)} 条）", expanded=True):
            img_ev = [a for a in image_anchors if (a.get("binding_type") or "").startswith("image_evidence")]
            txt_only = [a for a in image_anchors if a.get("binding_type") == "text_claim_only"]
            if img_ev:
                st.markdown("**影像证据**")
                for a in img_ev:
                    ref = a.get("image_ref") or "—"
                    region = a.get("region_tag") or ""
                    axis = a.get("axis_ref")
                    axis_str = f"axis {axis}" if axis is not None else ""
                    claim = a.get("claim_id") or a.get("claim_excerpt") or "—"
                    parts = [p for p in [ref, region, axis_str] if p]
                    st.markdown(f"- **{claim}** — {' · '.join(parts)}")
            if txt_only:
                st.markdown("**文献 / 文本依据**")
                for a in txt_only:
                    region = a.get("region_tag") or "—"
                    claim = a.get("claim_id") or "—"
                    st.markdown(f"- **{claim}** — {region}")

    # IX-4 W9: measurement-serves-diagnosis surface (RD-1a)
    render_w9_surface(case)

    # ── Quality flags ──
    flags = meta.get("uncertainty_flags", [])
    if flags:
        with st.expander("分析质量标记"):
            st.warning("不确定性标记: " + ", ".join(flags))

    # ── Audit trace ──
    with st.expander("显示审计追踪"):
        try:
            audit = api_client.get_case_audit(case_id)
            entries = audit.get("entries", [])
            total = audit.get("total", len(entries))
            st.caption(f"共 {total} 条追踪记录 | trace_id: {audit.get('trace_id', '—')}")
            if entries:
                for e in entries:
                    phase = e.get("phase", "?")
                    agent = e.get("agent") or e.get("from") or "—"
                    msg_type = e.get("msg_type", "")
                    ts = e.get("timestamp", "")[:19] if e.get("timestamp") else ""
                    st.markdown(f"**[{ts}] Phase {phase} · {agent}** `{msg_type}`")
                    payload = e.get("payload") or e.get("content") or {}
                    if payload:
                        st.json(payload)
            else:
                st.caption("暂无追踪条目（audit log 未写入或 case_id 未匹配）。")
        except Exception as ex:
            st.caption(f"加载审计追踪失败: {ex}")

    # ── Layer 2 assistant playbook (Scene 1 only, shown via caller's role check) ──
    layer_2 = fo.get("layer_2")
    if layer_2:
        with st.expander("👥 助理 playbook（内部使用）", expanded=True):
            st.caption("⚠️ 内部使用 — 严禁转发患者")

            # New schema: followup_questions / red_flags / communication_boundary
            followup = layer_2.get("followup_questions") or []
            if followup:
                st.markdown("**追问建议**")
                for q in followup:
                    st.markdown(f"- {q}")

            red_flags = layer_2.get("red_flags") or []
            if red_flags:
                st.markdown("**拒诊风险信号**")
                for r in red_flags:
                    st.markdown(f"- {r}")

            boundaries = layer_2.get("communication_boundary") or []
            if boundaries:
                st.markdown("**沟通注意事项（CRITICAL）**")
                for b in boundaries:
                    btype = b.get("type", "")
                    action = b.get("action", "")
                    if action:
                        st.warning(f"🔴 **{btype}**: {action}")

            # Legacy schema fallback (old section_d / section_h structure)
            if not followup and not red_flags and not boundaries:
                sec_d = layer_2.get("section_d_followup_guide") or {}
                risks = sec_d.get("rejection_risk_signals") or []
                if risks:
                    st.markdown("**拒诊风险信号**")
                    for r in risks:
                        st.markdown(f"- {r}")
                sec_h = layer_2.get("section_h_communication_boundary") or {}
                constraints = sec_h.get("constraints") or []
                if constraints:
                    st.markdown("**沟通注意事项（CRITICAL）**")
                    for c in constraints:
                        ctype = c.get("type", "")
                        action = c.get("action", "")
                        if action:
                            st.warning(f"🔴 **{ctype}**: {action}")
